(let ((content (with-open-file (in "src/api/global-search.lisp" :direction :input)
                 (let ((data (make-string (file-length in))))
                   (read-sequence data in)
                   data))))
  (let ((open (count #\( content))
        (close (count #\) content)))
    (format t "Open parentheses: ~D~%" open)
    (format t "Close parentheses: ~D~%" close)
    (if (= open close)
        (progn (format t "BALANCED~%") (sb-ext:quit 0))
        (progn (format t "IMBALANCE DETECTED~%") (sb-ext:quit 1)))))
