;;; api-package.lisp --- Package definition for API layer

(defpackage #:cl-telegram/api
  (:nicknames #:cl-tg/api)
  (:use #:cl #:bordeaux-threads)
  (:export
   ;; Authentication State
   #:*auth-state*
   #:*auth-phone-number*
   #:*auth-code-info*
   #:*auth-connection*
   #:*auth-session-id*

   ;; Authentication API
   #:set-authentication-phone-number
   #:request-authentication-code
   #:check-authentication-code
   #:set-authentication-password
   #:register-user
   #:get-authentication-state

   ;; Session Management
   #:get-auth-session
   #:reset-auth-session
   #:authorized-p
   #:needs-phone-p
   #:needs-code-p
   #:needs-password-p
   #:needs-registration-p
   #:ensure-auth-connection
   #:close-auth-connection

   ;; TDLib Compatibility
   #:|setTdlibParameters|
   #:|setAuthenticationPhoneNumber|
   #:|requestAuthenticationCode|
   #:|checkAuthenticationCode|
   #:|checkAuthenticationPassword|
   #:|registerUser|

   ;; Demo
   #:demo-auth-flow

   ;; Messages API
   #:send-message
   #:get-messages
   #:delete-messages
   #:forward-messages
   #:edit-message
   #:get-message-history
   #:search-messages
   #:send-reaction
   #:send-file
   #:download-file
   #:send-photo
   #:send-document
   #:send-audio
   #:send-video
   #:*upload-part-size*
   #:*max-file-size*

   ;; Chats API
   #:get-chats
   #:get-chat
   #:create-private-chat
   #:get-chat-history
   #:create-basic-group-chat
   #:create-supergroup-chat
   #:get-chat-members
   #:add-chat-member
   #:remove-chat-member
   #:send-chat-action
   #:set-chat-title
   #:toggle-chat-muted
   #:clear-chat-history
   #:search-chats
   ;; Group/Channel Administration
   #:get-chat-administrators
   #:set-chat-administrator
   #:remove-chat-administrator
   #:ban-chat-member
   #:unban-chat-member
   #:restrict-chat-member
   #:create-chat-invite-link
   #:get-chat-invite-link
   #:revoke-chat-invite-link
   #:get-chat-invite-link-members
   #:make-admin-permissions
   #:permissions-to-bitmask
   #:bitmask-to-permissions
   #:make-member-restrictions
   ;; Polls and Voting
   #:make-poll
   #:send-poll
   #:stop-poll
   ;; Group Statistics and Logging
   #:get-group-statistics
   #:get-group-admin-log
   ;; Auto-Moderation
   #:add-auto-mod-rule
   #:remove-auto-mod-rule
   #:get-auto-mod-rules
   #:check-auto-mod
   ;; Member Approval
   #:enable-member-approval
   #:disable-member-approval
   #:get-pending-join-requests
   #:approve-join-request
   #:decline-join-request
   ;; Search and Discovery
   #:make-search-filter
   #:search-public-chats
   #:search-public-chats-multi
   #:search-chats
   #:search-chats-on-server
   #:search-recently-found-chats
   #:search-messages
   #:search-chat-messages
   #:search-secret-messages
   #:search-chat-members
   #:get-search-query-suggestions
   #:clear-search-history
   #:get-search-history
   #:global-search
   ;; Channel-Specific
   #:get-channel-members
   #:get-channel-full-info
   #:set-channel-description
   #:set-channel-username
   #:delete-channel
   #:export-channel-invite-link
   #:join-channel
   #:leave-channel
   ;; Channel Management (channels.lisp)
   #:get-channel
   #:get-my-channels
   #:create-channel
   #:set-channel-info
   #:set-channel-photo
   #:delete-channel-photo
   #:get-channel-administrators
   #:add-channel-administrator
   #:remove-channel-administrator
   #:ban-channel-user
   #:unban-channel-user
   #:get-channel-banned-users
   #:revoke-channel-invite-link
   #:create-channel-invite-link
   #:get-channel-invite-link-info
   #:broadcast-to-channel
   #:edit-channel-message
   #:delete-channel-message
   #:pin-channel-message
   #:unpin-channel-message
   #:get-channel-stats
   #:get-channel-post-stats
   #:get-message-reactions
   #:send-message-reaction
   #:remove-message-reaction
   #:get-recent-reactors
   #:set-available-reactions
   #:get-channel-post
   #:get-channel-posts
   #:get-pinned-messages
   #:get-post-comments
   #:send-comment
   #:render-channel-list
   #:render-broadcast-panel
   #:render-reaction-panel
   #:render-channel-stats
   #:channel-type-string
   #:clear-channel-cache
   #:clear-reaction-cache

   ;; Users API
   #:get-users
   #:get-user
   #:get-me
   #:search-users
   #:get-user-profile-photos
   #:get-user-full-info
   #:get-user-status
   #:get-contacts
   #:add-contact
   #:delete-contacts
   #:block-user
   #:unblock-user
   #:get-blocked-users
   #:set-bio

   ;; Updates
   #:set-update-handler
   #:remove-update-handler
   #:start-update-loop
   #:stop-update-loop

   ;; Update Handler
   #:make-update-handler
   #:update-handler

   ;; Translation (v0.25.0)
   #:translate-text
   #:translate-message
   #:translate-messages
   #:translate-chat-messages
   #:set-chat-language
   #:get-chat-language
   #:enable-auto-translation
   #:auto-translation-enabled-p
   #:register-auto-translation-handler
   #:unregister-auto-translation-handler
   #:get-translation-info
   #:list-supported-languages
   #:detect-language
   #:configure-translation-api
   #:get-cached-translation
   #:clear-translation-cache
   #:get-translation-history

   ;; Story Highlights (v0.25.0)
   #:create-story-highlight
   #:edit-story-highlight
   #:edit-highlight-cover
   #:delete-story-highlight
   #:reorder-story-highlights
   #:get-story-highlights
   #:get-story-highlight
   #:get-highlight-stories
   #:add-stories-to-highlight
   #:remove-stories-from-highlight
   #:set-highlight-privacy
   #:get-highlight-privacy
   #:view-highlight-stories
   #:clear-highlights-cache
   #:refresh-highlights
   #:get-highlight-count
   #:get-highlight-by-title
   #:search-highlights
   #:highlight-has-story-p
   #:archive-story-to-highlight
   #:create-highlight-from-archived-stories
   #:delete-multiple-highlights
   #:export-highlights

   ;; Channel Reactions & Emoji Status (v0.25.0)
   #:send-channel-message-reaction
   #:remove-channel-message-reaction
   #:get-channel-message-reactions
   #:get-channel-reaction-stats
   #:get-recent-channel-reactors
   #:get-channel-available-reactions
   #:set-channel-available-reactions
   #:set-emoji-status
   #:clear-emoji-status
   #:get-emoji-statuses
   #:get-user-emoji-status
   #:get-premium-emoji-statuses
   #:get-channel-reaction-analytics
   #:get-reaction-trend
   #:clear-reaction-cache
   #:clear-all-reaction-caches
   #:get-popular-reactions
   #:is-reaction-selected-p

   ;; Advanced Media Editing (v0.25.0)
   #:enhance-image
   #:adjust-image-brightness
   #:adjust-image-contrast
   #:adjust-image-saturation
   #:adjust-image-tonemap
   #:apply-professional-filter
   #:apply-cinematic-filter
   #:apply-vintage-filter
   #:apply-teal-orange-grade
   #:apply-vignette
   #:add-film-grain
   #:batch-process-images
   #:convert-image-format
   #:add-watermark
   #:add-logo-watermark
   #:resize-image
   #:denoise-image
   #:sharpen-image
   #:upscale-image
   #:auto-enhance-image

   ;; Group Video Call (v0.26.0)
   #:init-group-video
   #:shutdown-group-video
   #:start-group-video-stream
   #:stop-group-video-stream
   #:enable-screen-sharing
   #:disable-screen-sharing
   #:get-screen-share-streams
   #:set-video-quality
   #:get-video-quality
   #:get-group-video-layout
   #:pin-participant-video
   #:unpin-participant-video
   #:set-video-layout-type
   #:toggle-group-call-recording
   #:stop-group-call-recording
   #:get-group-call-recording
   #:enable-ai-noise-reduction
   #:disable-ai-noise-reduction
   #:get-group-video-stats
   #:get-participant-video-stats
   #:make-video-layout
   #:update-video-layout
   #:get-layout-grid
   #:get-quality-preset
   #:calculate-adaptive-quality

   ;; Video Messages (v0.26.0)
   #:start-video-message-recording
   #:stop-video-message-recording
   #:pause-video-message-recording
   #:resume-video-message-recording
   #:cancel-video-message-recording
   #:get-recording-progress
   #:process-video-message
   #:crop-video-to-circle
   #:compress-video
   #:generate-video-thumbnail
   #:send-video-message
   #:download-video-message
   #:parse-video-message
   #:play-video-message
   #:get-video-metadata
   #:is-valid-video-message

   ;; Media Albums (v0.26.0)
   #:create-media-album
   #:delete-media-album
   #:edit-media-album
   #:get-media-albums
   #:get-media-album
   #:add-media-to-album
   #:remove-media-from-album
   #:reorder-album-media
   #:auto-create-albums
   #:add-media-tags
   #:remove-media-tags
   #:search-media-by-tags
   #:get-popular-tags
   #:search-media
   #:filter-media-by-type
   #:get-media-timeline
   #:export-media-album
   #:export-all-media

   ;; Auto-Delete Messages (v0.27.0)
   #:set-message-timer
   #:cancel-message-timer
   #:get-message-timer-remaining
   #:set-chat-default-timer
   #:get-chat-default-timer
   #:clear-chat-default-timer
   #:start-auto-delete-monitor
   #:stop-auto-delete-monitor
   #:get-auto-delete-stats
   #:send-message-with-auto-delete
   #:list-active-timers
   #:cleanup-expired-timers

   ;; Chat Backup (v0.27.0)
   #:export-chat-history
   #:export-all-chats
   #:import-chat-history
   #:create-incremental-backup
   #:get-backup-info

   ;; Global Search (v0.27.0)
   #:global-search-messages
   #:search-in-chat
   #:get-search-suggestions
   #:highlight-search-result
   #:format-search-results
   #:search-messages-by-sender
   #:search-messages-by-date-range
   #:search-messages-by-media-type
   #:clear-search-cache
   #:get-search-cache-stats
   #:set-search-cache-ttl
   #:get-search-history
   #:clear-search-history

   ;; Media Library (v0.27.0)
   #:get-all-media
   #:get-all-photos
   #:get-all-videos
   #:get-all-documents
   #:get-all-audio
   #:get-all-files
   #:get-chat-media
   #:search-files
   #:filter-media-by-chat
   #:sort-media-by-date
   #:group-media-by-month
   #:download-media-batch
   #:delete-media-batch
   #:get-media-statistics
   #:get-media-usage-by-chat
   #:get-media-usage-by-type
   #:get-media-item
   #:clear-media-cache
   #:get-media-cache-stats
   #:set-media-cache-ttl
   #:detect-media-type
   #:get-file-extension
   #:export-media-list

   ;; Custom Themes (v0.27.0)
   #:create-theme
   #:delete-theme
   #:get-theme
   #:list-themes
   #:set-theme-color
   #:get-theme-colors
   #:apply-theme
   #:set-chat-background
   #:get-chat-background
   #:reset-chat-background
   #:set-font-size
   #:set-app-icon
   #:export-theme
   #:import-theme
   #:get-theme-presets
   #:apply-theme-preset
   #:clear-theme-cache
   #:get-theme-stats

   #:register-update-handler
   #:unregister-update-handler
   #:clear-update-handlers
   #:dispatch-update
   #:process-update-object
   #:update-stats
   #:with-update-handler

   ;; Bot API - Configuration
   #:make-bot
   #:bot-config
   #:make-bot-config
   #:bot-config-token
   #:bot-config-api-url
   #:bot-config-timeout
   #:bot-config-use-test-environment

   ;; Bot API - Core
   #:bot-request
   #:get-me
   #:get-my-name
   #:get-my-description
   #:get-my-short-description

   ;; Bot API - Sending Messages
   #:bot-send-message
   #:bot-send-photo
   #:bot-send-document
   #:bot-send-sticker
   #:bot-send-location
   #:bot-send-chat-action
   #:bot-edit-message-text
   #:bot-delete-message

   ;; Bot API - Updates
   #:get-updates
   #:set-webhook
   #:delete-webhook
   #:get-webhook-info

   ;; Bot API - Chat Management
   #:bot-get-chat
   #:bot-get-chat-member
   #:bot-get-chat-administrators
   #:bot-ban-chat-member
   #:bot-unban-chat-member
   #:bot-restrict-chat-member

   ;; Bot API - Handlers
   #:make-bot-handler
   #:bot-handler
   #:defcommand
   #:register-command
   #:unregister-command
   #:register-message-handler
   #:process-update
   #:start-polling
   #:stop-polling
   #:setup-basic-commands
   #:register-inline-handler
   #:answer-inline-query

   ;; Secret Chats (E2E Encryption)
   #:make-secret-chat-manager
   #:*secret-chat-manager*
   #:secret-chat
   #:secret-chat-manager
   #:request-secret-chat
   #:accept-secret-chat-request
   #:get-secret-chat
   #:get-secret-chat-with-user
   #:list-secret-chats
   #:close-secret-chat
   #:send-secret-message
   #:send-secret-media
   #:send-secret-chat-action
   #:set-secret-chat-ttl
   #:mark-secret-messages-read
   #:delete-secret-messages
   #:handle-encrypted-message-update
   ;; E2E Encryption Enhancements
   #:create-new-secret-chat
   #:accept-secret-chat
   #:verify-key-fingerprint
   #:get-key-fingerprint-visual
   #:send-encrypted-photo
   #:send-encrypted-video
   #:send-encrypted-document
   #:set-message-ttl
   #:schedule-message-self-destruct
   #:detect-screenshot-attempt
   #:prevent-message-forwarding
   #:enable-anti-screenshot
   #:get-secret-chat-stats
   #:cleanup-expired-secret-chats
   #:clear-secret-chat-history

   ;; Local Database Cache
   #:init-database
   #:close-database
   #:cache-user
   #:get-cached-user
   #:search-cached-users
   #:cache-chat
   #:get-cached-chat
   #:list-cached-chats
   #:cache-message
   #:cache-messages
   #:get-cached-messages
   #:get-cached-message
   #:search-cached-messages
   #:delete-cached-message
   #:clear-chat-cache
   #:cache-secret-chat
   #:get-cached-secret-chat
   #:cache-session
   #:get-current-session
   #:get-cached-auth-key
   #:cache-file-info
   #:get-cached-file-path
   #:set-setting
   #:get-setting
   #:get-database-stats
   #:vacuum-database
   #:clear-all-cache

   ;; VoIP / Calls
   #:make-call-manager
   #:*call-manager*
   #:init-voip
   #:close-voip
   #:make-call-protocol
   #:create-call
   #:accept-call
   #:decline-call
   #:end-call
   #:toggle-call-mute
   #:toggle-call-video
   #:get-call
   #:list-active-calls
   #:get-call-stats
   ;; Group Calls
   #:create-group-call
   #:join-group-call
   #:leave-group-call
   #:toggle-group-call-mute
   #:toggle-group-call-video
   #:get-group-call-participants
   #:get-group-call
   #:list-active-group-calls
   #:get-group-call-stats
   ;; WebRTC
   #:generate-webrtc-offer
   #:generate-webrtc-answer
   #:handle-ice-candidate
   ;; WebRTC FFI
   #:*webrtc-manager*
   #:*webrtc-initialized*
   #:init-webrtc
   #:shutdown-webrtc
   #:create-webrtc-peer-connection
   #:close-webrtc-peer-connection
   #:create-webrtc-media-stream
   #:close-webrtc-media-stream
   #:create-webrtc-offer
   #:create-webrtc-answer
   #:set-webrtc-remote-description
   #:add-webrtc-ice-candidate
   #:create-webrtc-data-channel
   #:send-webrtc-data
   #:close-webrtc-data-channel
   #:get-webrtc-state
   #:get-webrtc-signaling-state
   #:start-webrtc-call
   #:accept-webrtc-call
   #:add-webrtc-candidate-to-call
   #:webrtc-stats
   #:test-webrtc-connection
   #:get-pending-ice-candidates

   ;; Performance Optimizations
   #:get-cached-messages-optimized
   #:get-cached-chat-optimized
   #:start-connection-pool-cleaner
   #:stop-connection-pool-cleaner
   #:get-connection-from-pool-optimized
   #:cache-message-in-memory
   #:get-cached-messages-in-memory
   #:clear-message-cache
   #:batch-get-cached-users
   #:batch-cache-messages
   #:with-performance-monitoring
   #:record-performance-metric
   #:get-performance-stats
   #:reset-performance-stats
   #:optimize-database

   ;; Stickers & Emoji
   #:sticker
   #:sticker-set
   #:emoji-pack
   #:sticker-file-id
   #:sticker-file-unique-id
   #:sticker-width
   #:sticker-height
   #:sticker-is-animated
   #:sticker-is-video
   #:sticker-thumbnail
   #:sticker-emoji
   #:sticker-set-name
   #:sticker-set-title
   #:sticker-set-stickers
   #:sticker-set-emoji-representation
   #:emoji-pack-id
   #:emoji-pack-title
   #:emoji-pack-emoji-list
   #:emoji-pack-is-installed
   #:*sticker-cache*
   #:*emoji-packs*
   #:*favorite-stickers*
   #:get-sticker-set
   #:search-sticker-sets
   #:get-all-sticker-sets
   #:install-sticker-set
   #:uninstall-sticker-set
   #:add-sticker-to-set
   #:remove-sticker-from-set
   #:upload-sticker
   #:create-new-sticker-set
   #:get-favorite-stickers
   #:add-favorite-sticker
   #:remove-favorite-sticker
   #:get-emoji-packs
   #:install-emoji-pack
   #:uninstall-emoji-pack
   #:get-installed-emoji-packs
   #:send-sticker
   #:get-sticker-from-message
   #:send-custom-emoji
   #:get-custom-emoji
   #:search-stickers
   #:get-trending-stickers
   #:render-sticker-picker
   #:render-emoji-picker
   #:sticker-dimension-string
   #:sticker-type-string
   #:clear-sticker-cache

   ;; Sticker Management
   #:get-sticker-set
   #:search-sticker-sets
   #:get-all-sticker-sets
   #:install-sticker-set
   #:uninstall-sticker-set
   #:add-sticker-to-set
   #:remove-sticker-from-set
   #:upload-sticker
   #:create-new-sticker-set
   #:get-favorite-stickers
   #:add-favorite-sticker
   #:remove-favorite-sticker
   #:get-emoji-packs
   #:install-emoji-pack
   #:uninstall-emoji-pack
   #:get-installed-emoji-packs
   #:send-sticker
   #:get-sticker-from-message
   #:send-custom-emoji
   #:get-custom-emoji

   ;; Channels & Broadcast
   #:channel
   #:channel-post
   #:message-reaction
   #:channel-id
   #:channel-title
   #:channel-description
   #:channel-username
   #:channel-photo
   #:channel-member-count
   #:channel-is-broadcast
   #:channel-is-megagroup
   #:channel-is-admin
   #:channel-is-owner
   #:channel-can-post-messages
   #:channel-can-edit-messages
   #:channel-can-delete-messages
   #:channel-linked-chat-id
   #:channel-post-id
   #:channel-post-channel-id
   #:channel-post-text
   #:channel-post-media
   #:channel-post-date
   #:channel-post-views
   #:channel-post-forwards
   #:channel-post-reactions
   #:channel-post-comments-count
   #:channel-post-is-pinned
   #:message-reaction-id
   #:message-reaction-message-id
   #:message-reaction-chat-id
   #:message-reaction-emoji
   #:message-reaction-count
   #:message-reaction-is-selected
   #:message-reaction-recent-reactors
   #:*channel-cache*
   #:*available-reactions*
   #:*recent-reactions*

   ;; Inline Bots & Keyboards
   #:inline-query
   #:inline-result
   #:chosen-inline-result
   #:inline-keyboard-button
   #:inline-keyboard-markup
   #:callback-query
   #:reply-keyboard-button
   #:reply-keyboard-markup
   #:reply-keyboard-remove
   #:force-reply
   #:web-app-info
   #:web-app-data
   #:inline-query-id
   #:inline-query-from
   #:inline-query-query
   #:inline-query-offset
   #:inline-query-chat-type
   #:inline-query-location
   #:inline-result-id
   #:inline-result-type
   #:inline-result-title
   #:inline-result-description
   #:inline-result-message-text
   #:inline-result-input-message-content
   #:inline-result-reply-markup
   #:chosen-result-id
   #:chosen-result-from
   #:chosen-result-location
   #:chosen-inline-message-id
   #:chosen-result-query
   #:inline-button-text
   #:inline-button-url
   #:inline-button-callback-data
   #:inline-button-switch-inline
   #:inline-button-switch-bot
   #:inline-button-web-app
   #:inline-keyboard-keyboard
   #:inline-keyboard-resize
   #:inline-keyboard-one-time
   #:inline-keyboard-selective
   #:callback-query-id
   #:callback-query-from
   #:callback-query-message
   #:callback-query-inline-message-id
   #:callback-query-chat-instance
   #:callback-query-data
   #:callback-query-game-short-name
   #:reply-button-text
   #:reply-button-request-user
   #:reply-button-request-chat
   #:reply-button-request-contact
   #:reply-button-request-location
   #:reply-button-request-poll
   #:reply-button-web-app
   #:reply-keyboard-keyboard
   #:reply-keyboard-resize
   #:reply-keyboard-one-time
   #:reply-keyboard-persistent
   #:reply-keyboard-selective
   #:reply-keyboard-placeholder
   #:reply-keyboard-remove-p
   #:reply-keyboard-remove-selective
   #:force-reply-p
   #:force-reply-selective
   #:force-reply-placeholder
   #:web-app-url
   #:web-app-button-text
   #:web-app-start-param
   #:web-app-query-id
   #:web-app-chat-type
   #:web-app-chat-instance
   #:*inline-bot-handlers*
   #:*callback-query-handlers*
   #:*command-handlers*
   #:*inline-bot-token*
   #:register-inline-bot-handler
   #:unregister-inline-bot-handler
   #:dispatch-inline-query
   #:dispatch-callback-query
   #:answer-inline-query
   #:answer-callback-query
   #:make-inline-result-article
   #:make-inline-result-photo
   #:make-inline-result-gif
   #:make-inline-result-sticker
   #:make-inline-result-video
   #:make-inline-result-audio
   #:make-inline-result-voice
   #:make-inline-result-location
   #:make-inline-result-venue
   #:make-inline-result-contact
   #:make-inline-result-game
   #:make-inline-keyboard-button
   #:make-inline-keyboard
   #:make-reply-keyboard-button
   #:make-reply-keyboard
   #:make-reply-keyboard-remove
   #:make-force-reply
   #:make-web-app-button
   #:send-web-app-data
   #:process-inline-update
   #:parse-inline-query
   #:parse-callback-query
   #:render-inline-keyboard
   #:render-reply-keyboard
   #:show-inline-results
   #:keyboard-button-p
   #:clear-keyboard-cache
   #:get-inline-bot-token
   #:set-inline-bot-token

   ;; Inline Bot 2025 Improvements
   #:inline-result-visual-effect
   #:inline-result-with-effects
   #:business-inline-config
   #:paid-media-info
   #:web-app-inline-button
   #:inline-query-context
   #:visual-effect-type
   #:visual-effect-start-x
   #:visual-effect-start-y
   #:visual-effect-end-x
   #:visual-effect-end-y
   #:visual-effect-intensity
   #:effects-result
   #:effects-visual-effects
   #:effects-animation-type
   #:business-location
   #:business-hours
   #:business-start-message
   #:business-can-send-paid-media
   #:paid-media-type
   #:paid-media-url
   #:paid-media-price
   #:paid-media-currency
   #:paid-media-is-paid
   #:webapp-button-text
   #:webapp-button-url
   #:webapp-button-forward-text
   #:webapp-button-type
   #:context-switch-pm-param
   #:context-switch-pm-text
   #:context-gallery-layout
   #:context-personal-results
   #:make-visual-effect
   #:add-visual-effects-to-result
   #:make-business-inline-config
   #:make-paid-media-info
   #:make-webapp-inline-button
   #:make-inline-query-context
   #:answer-inline-query-extended
   #:send-paid-media
   #:get-business-connection
   #:get-user-chat-boosts
   #:make-inline-result-story
   #:make-inline-result-giveaway
   #:make-inline-result-with-spoiler
   #:make-inline-result-extended-media
   #:inline-result-has-effects-p
   #:apply-visual-effect-to-result
   #:get-enhanced-inline-features

   ;; Premium Features
   #:premium-status
   #:premium-features-config
   #:*premium-status*
   #:*premium-features-config*
   #:*premium-cache-ttl*
   #:*premium-last-check*
   #:check-premium-status
   #:refresh-premium-status
   #:get-premium-status-from-server
   #:verify-premium-status
   #:premium-required-p
   #:ensure-premium
   #:premium-required-error
   #:premium-error-feature
   #:premium-error-message
   #:get-max-file-size
   #:can-upload-file-p
   #:validate-file-for-upload
   #:get-premium-sticker-sets
   #:fetch-premium-sticker-sets
   #:can-use-premium-sticker-p
   #:get-premium-reactions
   #:fetch-premium-reactions
   #:can-send-reaction-p
   #:get-premium-profile-colors
   #:fetch-premium-profile-colors
   #:get-premium-chat-themes
   #:fetch-premium-chat-themes
   #:set-profile-color
   #:set-chat-theme
   #:get-premium-emoji-statuses
   #:fetch-premium-emoji-statuses
   #:set-emoji-status
   #:clear-emoji-status
   #:get-premium-transcription-hours
   #:transcribe-voice-message-premium
   #:get-doubled-limits
   #:can-pin-more-chats-p
   #:can-join-more-channels-p
   #:render-premium-badge
   #:render-premium-features-panel
   #:show-premium-promo
   #:get-premium-stats
   #:reset-premium-cache
   #:get-premium-subscription-info
   #:cancel-premium-subscription
   #:renew-premium-subscription

   ;; Inline Bot 2025 Extended (Bot API 9.1+)
   #:make-inline-result-article-with-effects
   #:make-inline-result-photo-with-effects
   #:make-inline-result-video-with-effects
   #:make-inline-result-gif-with-effects
   #:send-inline-result-with-animation
   #:get-inline-bot-analytics
   #:set-inline-bot-business-location
   #:set-inline-bot-business-hours
   #:create-paid-media-post
   #:answer-web-app-query
   #:get-web-app-init-data
   #:validate-web-app-init-data
   #:send-business-message
   #:edit-business-message
   #:delete-business-message
   #:get-business-connection-info
   #:list-business-connections
   #:close-business-connection

   ;; File Management
   #:file-location
   #:uploaded-file
   #:web-file
   #:get-file-location
   #:download-file
   #:download-file-partial
   #:download-media
   #:upload-file
   #:upload-file-small
   #:upload-file-large
   #:upload-media
   #:get-web-file
   #:get-upload-session
   #:cancel-upload
   #:get-upload-progress
   #:get-active-uploads
   #:enable-cdn-download
   #:disable-cdn-download
   #:cdn-download-enabled-p
   #:set-cdn-config
   #:file-size-string
   #:format-upload-speed
   #:estimate-upload-time
   #:determine-media-type
   #:guess-mime-type
   #:*file-download-queue*
   #:*active-uploads*
   #:*download-part-size*
   #:*upload-part-size*
   #:*max-upload-parts*
   #:*cdn-download-enabled*

   ;; Drafts and Scheduled Messages
   #:draft-message
   #:save-draft
   #:get-drafts
   #:get-all-drafts
   #:get-draft
   #:delete-draft
   #:clear-all-drafts
   #:send-scheduled-message
   #:send-scheduled-media
   #:get-scheduled-messages
   #:get-all-scheduled-messages
   #:delete-scheduled-message
   #:delete-all-scheduled-messages
   #:send-scheduled-messages-now
   #:set-default-message-ttl
   #:get-default-message-ttl
   #:set-chat-ttl
   #:send-multi-media
   #:send-photo-album
   #:send-video-album
   #:copy-message
   #:*draft-cache*
   #:*scheduled-messages*
   #:*default-ttl*

   ;; Account Security
   #:login-token
   #:authorization-session
   #:privacy-rule
   #:export-login-token
   #:import-login-token
   #:accept-login-token
   #:generate-qr-code-url
   #:parse-qr-code-url
   #:get-privacy-settings
   #:set-privacy-settings
   #:reset-privacy-settings
   #:get-authorizations
   #:reset-authorization
   #:reset-authorization-all
   #:change-phone-number
   #:send-confirm-phone-code
   #:confirm-phone
   #:takeout-init
   #:finish-takeout-session
   #:base64-encode
   #:base64-decode
   #:*login-token*
   #:*qr-login-state*
   #:*privacy-rules-cache*

   ;; Payment and Telegram Stars (v0.20.0)
   #:labeled-price
   #:invoice
   #:star-transaction
   #:star-balance
   #:make-labeled-price
   #:make-invoice
   #:send-invoice
   #:create-invoice-link
   #:refund-star-payment
   #:gift-premium-subscription
   #:get-business-account-star-balance
   #:transfer-business-account-stars
   #:create-subscription-invoice
   #:create-star-invoice
   #:*supported-currencies*
   #:*max-tip-presets*

   ;; Business Features (v0.20.0)
   #:business-connection
   #:business-location
   #:business-opening-hours
   #:business-opening-hours-interval
   #:business-bot-rights
   #:quick-reply
   #:get-business-connection
   #:list-business-connections
   #:set-business-location
   #:get-business-location
   #:delete-business-location
   #:make-opening-hours-interval
   #:make-opening-hours-from-times
   #:set-business-opening-hours
   #:get-business-opening-hours
   #:delete-business-opening-hours
   #:make-quick-reply
   #:send-message-with-quick-replies
   #:send-business-message
   #:edit-business-message
   #:delete-business-message
   #:create-business-chat-link
   #:*business-connections-cache*
   #:*quick-reply-types*

   ;; Chat Folders (v0.21.0)
   #:chat-folder
   #:chat-folder-filter
   #:archive-info
   #:make-chat-folder
   #:make-chat-folder-filter
   #:create-chat-folder
   #:edit-chat-folder
   #:delete-chat-folder
   #:get-chat-folders
   #:get-chat-folder
   #:add-chat-to-folder
   #:remove-chat-from-folder
   #:archive-chat
   #:unarchive-chat
   #:get-archived-chats
   #:get-archive-info
   #:get-chat-list
   #:reorder-chat-folders
   #:share-chat-folder
   #:import-chat-folder
   #:*chat-folders-cache*
   #:*archive-cache*
   #:*default-folder-icons*

   ;; Emoji and Customization (v0.21.0)
   #:custom-emoji
   #:emoji-category
   #:message-effect
   #:chat-wallpaper
   #:chat-theme
   #:get-custom-emoji-stickers
   #:get-emoji-categories
   #:search-custom-emoji
   #:get-premium-emojis
   #:get-available-message-effects
   #:send-message-with-effect
   #:send-dice
   #:get-wallpapers
   #:set-chat-wallpaper
   #:upload-wallpaper
   #:get-chat-themes
   #:set-chat-theme
   #:get-premium-themes
   #:send-star-reaction
   #:create-giveaway
   #:*custom-emoji-cache*
   #:*wallpaper-cache*
   #:*theme-cache*
   #:*available-message-effects*
   #:*default-dice-emojis*

   ;; Channel Advanced Features (v0.21.0)
   #:forum-topic
   #:forum-topic-info
   #:channel-statistics
   #:message-statistics
   #:reaction-statistics
   #:sponsored-message
   #:create-forum-topic
   #:get-forum-topics
   #:edit-forum-topic
   #:close-forum-topic
   #:reopen-forum-topic
   #:delete-forum-topic
   #:pin-forum-topic
   #:unpin-forum-topic
   #:get-forum-topic-icon-stickers
   #:get-channel-statistics
   #:get-message-statistics
   #:get-reaction-statistics
   #:get-sponsored-messages
   #:report-sponsored-message
   #:*forum-topics-cache*
   #:*channel-stats-cache*
   #:*sponsored-messages-cache*
   #:*topic-icon-colors*

   ;; Performance Monitoring
   #:start-performance-monitoring
   #:stop-performance-monitoring
   #:record-metric
   #:get-performance-stats
   #:reset-performance-stats
   #:with-timing
   #:time-operation
   #:get-memory-usage
   #:trigger-garbage-collection
   #:record-connection-stats
   #:get-connection-pool-stats
   #:reset-connection-pool-stats
   #:cleanup-stale-connections
   #:optimize-connection-pool
   #:get-cache-stats
   #:record-cache-hit
   #:record-cache-miss
   #:record-cache-eviction
   #:implement-lru-eviction
   #:optimize-message-cache
   #:record-error
   #:get-error-rates
   ;; Stability
   #:implement-auto-reconnect
   #:make-auto-reconnect
   #:exponential-backoff
   #:with-retry
   #:setup-error-handling
   #:make-circuit-breaker
   #:circuit-breaker-allow-request-p
   #:circuit-breaker-record-success
   #:circuit-breaker-record-failure
   #:get-circuit-breaker-state
   #:with-circuit-breaker
   #:register-health-check
   #:unregister-health-check
   #:run-health-check
   #:run-all-health-checks
   #:get-health-status
   #:setup-default-health-checks
   #:cleanup-resources
   #:log-message
   #:set-log-level
   #:with-performance-monitoring

   ;; Media Editing
   #:edit-message-text
   #:edit-message-caption
   #:edit-message-media
   #:edit-message-reply-markup
   #:edit-message-live-location
   #:stop-message-live-location
   #:edit-message-checklist
   #:edit-message
   #:crop-media
   #:rotate-media
   #:apply-filter
   #:generate-thumbnail
   #:add-text-overlay
   #:add-emoji-sticker
   #:make-input-media-photo
   #:make-input-media-video
   #:make-input-media-audio
   #:make-input-media-document
   #:make-input-media-animation

   ;; Desktop Notifications
   #:make-notification-manager
   #:initialize-notifications
   #:send-notification
   #:set-quiet-hours
   #:disable-quiet-hours
   #:get-notification-history
   #:clear-notification-history
   #:show-notification-preview
   #:setup-notification-handlers
   #:*notification-manager*

   ;; Real-time Updates (WebSocket)
   #:make-websocket-client
   #:connect-websocket
   #:close-websocket
   #:send-websocket-message
   #:enable-realtime-updates
   #:disable-realtime-updates
   #:websocket-stats
   #:*websocket-update-handler*

   ;; Message Replies & Threads
   #:message-reply
   #:message-thread
   #:reply-chain
   #:message-reply-id
   #:message-reply-message-id
   #:message-reply-chat-id
   #:message-reply-to-id
   #:message-reply-from
   #:message-reply-text
   #:message-reply-date
   #:message-reply-quote-text
   #:message-reply-quote-entities
   #:message-thread-id
   #:message-thread-chat-id
   #:message-thread-topic
   #:message-thread-root-id
   #:message-thread-message-count
   #:message-thread-unread-count
   #:message-thread-last-id
   #:message-thread-last-date
   #:message-thread-participants
   #:message-thread-is-closed
   #:message-thread-is-pinned
   #:reply-chain-id
   #:reply-chain-message-id
   #:reply-chain-chat-id
   #:reply-chain-replies
   #:reply-chain-total-count
   #:*reply-cache*
   #:*thread-cache*
   #:*active-threads*
   #:send-message-with-reply
   #:get-message-replies
   #:get-reply-to-message
   #:edit-message-with-reply
   #:forward-message-with-reply
   #:create-message-thread
   #:get-message-thread
   #:get-threads-by-chat
   #:get-active-threads
   #:get-closed-threads
   #:send-message-to-thread
   #:close-message-thread
   #:reopen-message-thread
   #:pin-message-thread
   #:unpin-message-thread
   #:delete-message-thread
   #:edit-message-thread
   #:get-reply-chain
   #:add-reply-to-chain
   #:get-thread-messages
   #:make-quote-text
   #:parse-quote-from-message
   #:get-thread-stats
   #:get-thread-participants
   #:add-participant-to-thread
   #:remove-participant-from-thread
   #:render-reply-preview
   #:render-message-thread
   #:render-thread-view
   #:render-thread-list-panel
   #:render-thread-list-content
   #:get-thread-by-root-message
   #:clear-thread-cache
   #:clear-reply-cache
   #:thread-is-active-p
   #:get-reply-count

   ;; Voice & Audio Messages
   #:voice-message
   #:audio-message
   #:video-message
   #:recording-state
   #:voice-file-id
   #:voice-file-unique-id
   #:voice-duration
   #:voice-mime-type
   #:voice-file-size
   #:voice-waveform
   #:voice-is-transcribing
   #:voice-transcription
   #:voice-transcription-language
   #:audio-file-id
   #:audio-file-unique-id
   #:audio-duration
   #:audio-mime-type
   #:audio-file-size
   #:audio-title
   #:audio-performer
   #:audio-thumbnail
   #:video-file-id
   #:video-file-unique-id
   #:video-duration
   #:video-mime-type
   #:video-file-size
   #:video-width
   #:video-height
   #:video-thumbnail
   #:video-has-audio
   #:recording-is-active
   #:recording-start-time
   #:recording-duration
   #:recording-amplitude
   #:recording-waveform-data
   #:recording-device-id
   #:voice-chat
   #:voice-chat-chat-id
   #:voice-chat-is-active
   #:voice-chat-participants
   #:voice-chat-start-date
   #:voice-chat-duration
   #:voice-chat-is-muted
   #:voice-chat-is-video-enabled
   #:*voice-message-cache*
   #:*recording-state*
   #:*available-voice-devices*
   #:*voice-transcription-handlers*
   #:send-voice-message
   #:send-voice-file
   #:record-voice-message
   #:cancel-voice-recording
   #:finish-voice-recording
   #:get-voice-message
   #:get-voice-messages
   #:generate-waveform
   #:render-waveform-svg
   #:decode-waveform-from-base64
   #:encode-waveform-to-base64
   #:register-transcription-handler
   #:transcribe-voice-message
   #:request-voice-transcription
   #:play-voice-message
   #:stop-voice-playback
   #:pause-voice-playback
   #:resume-voice-playback
   #:send-audio-file
   #:get-audio-file
   #:send-video-message
   #:record-video-message
   #:start-voice-chat
   #:end-voice-chat
   #:join-voice-chat
   #:leave-voice-chat
   #:invite-to-voice-chat
   #:toggle-voice-chat-mute
   #:render-voice-message
   #:render-voice-recorder
   #:show-voice-chat-panel
   #:render-transcription
   #:voice-message-duration-string
   #:waveform-to-ascii
   #:clear-voice-cache
   #:get-available-voice-devices
   #:send-audio-by-file-id
   #:make-temp-audio-file
   #:make-temp-video-file
   #:upload-file
   #:download-file-to-cache
   #:guess-audio-duration
   #:generate-waveform-from-file
   #:parse-voice-message-from-message
   #:register-transcription-callback
   #:premium-feature-available-p

   ;; Stories & Highlights
   #:story
   #:story-highlight
   #:story-privacy
   #:stories-state
   #:story-id
   #:story-owner
   #:story-date
   #:story-expiration-date
   #:story-media
   #:story-caption
   #:story-is-pinned
   #:story-privacy
   #:story-can-reply
   #:story-can-reshare
   #:story-views-count
   #:story-reactions
   #:story-is-viewed
   #:story-is-forwarded
   #:highlight-id
   #:highlight-title
   #:highlight-cover-media
   #:highlight-stories
   #:highlight-date-created
   #:story-privacy-type
   #:story-privacy-allowed
   #:story-privacy-blocked
   #:story-privacy-is-dark
   #:stories-has-unviewed
   #:stories-unviewed-count
   #:stories-active-story-id
   #:stories-current-index
   #:*stories-cache*
   #:*highlights-cache*
   #:*stories-state*
   #:*stories-upload-queue*
   #:*story-effects-cache*
   #:*active-story-animation*
   #:get-stories
   #:get-all-stories
   #:get-unviewed-stories
   #:get-story-by-id
   #:post-story
   #:post-story-photo
   #:post-story-video
   #:delete-story
   #:edit-story
   #:pin-story
   #:unpin-story
   #:set-story-privacy
   #:get-story-privacy-settings
   #:mark-story-viewed
   #:send-story-reaction
   #:get-story-views
   #:get-story-reactions
   #:forward-story
   #:reply-to-story
   #:create-highlight
   #:get-highlights
   #:get-highlight
   #:edit-highlight
   #:add-stories-to-highlight
   #:remove-highlight
   #:view-next-story
   #:view-previous-story
   #:close-stories-viewer
   #:get-expiring-stories
   #:cleanup-expired-stories
   #:get-story-stats
   #:get-stories-stats
   #:render-stories-bar
   #:render-stories-viewer
   #:render-highlight
   #:render-highlights-list
   #:story-is-expired-p
   #:story-time-remaining
   #:format-story-time
   #:clear-stories-cache
   #:clear-highlights-cache

   ;; Story Animations and Effects (v0.13.0)
   #:story-animation
   #:story-filter
   #:story-music
   #:story-drawing
   #:story-text-style
   #:story-animation-type
   #:story-animation-id
   #:story-animation-duration
   #:story-animation-delay
   #:story-animation-intensity
   #:story-filter-type
   #:story-filter-intensity
   #:story-filter-settings
   #:story-music-title
   #:story-music-artist
   #:story-music-url
   #:story-music-duration
   #:story-music-start-time
   #:story-drawing-color
   #:story-drawing-strokes
   #:story-drawing-tool
   #:story-text-font
   #:story-text-size
   #:story-text-color
   #:story-text-background
   #:story-text-alignment
   #:*available-story-animations*
   #:*available-story-filters*
   #:*story-effect-presets*
   #:make-story-animation
   #:make-story-filter
   #:make-story-music
   #:make-story-drawing
   #:make-story-text-style
   #:apply-animation-to-story
   #:apply-filter-to-story
   #:apply-music-to-story
   #:apply-drawing-to-story
   #:apply-text-style-to-story
   #:post-story-with-animation
   #:post-story-with-filter
   #:post-story-with-music
   #:post-story-with-drawing
   #:apply-story-preset
   #:create-drawing-stroke
   #:create-emoji-sticker
   #:create-text-overlay
   #:render-story-animation
   #:get-story-effects
   #:remove-story-effects
   #:preview-story-effect
   #:clear-story-effects-cache

   ;; Telegram Premium
   #:premium-status
   #:premium-features-config
   #:*premium-status*
   #:*premium-features-config*
   #:*premium-cache-ttl*
   #:*premium-last-check*
   #:premium-is-premium
   #:premium-expiration-date
   #:premium-subscription-type
   #:premium-can-send-large-files
   #:premium-can-use-premium-stickers
   #:premium-max-file-size
   #:premium-max-download-speed
   #:premium-double-limits
   #:config-premium-sticker-sets
   #:config-premium-reactions
   #:config-premium-emoji-statuses
   #:config-premium-profile-colors
   #:config-premium-chat-themes
   #:config-premium-transcription-hours
   #:check-premium-status
   #:refresh-premium-status
   #:get-premium-status-from-server
   #:verify-premium-status
   #:premium-required-p
   #:ensure-premium
   #:premium-required-error
   #:premium-error-feature
   #:premium-error-message
   #:get-max-file-size
   #:can-upload-file-p
   #:validate-file-for-upload
   #:get-premium-sticker-sets
   #:fetch-premium-sticker-sets
   #:can-use-premium-sticker-p
   #:get-premium-reactions
   #:fetch-premium-reactions
   #:can-send-reaction-p
   #:get-premium-profile-colors
   #:fetch-premium-profile-colors
   #:get-premium-chat-themes
   #:fetch-premium-chat-themes
   #:set-profile-color
   #:set-chat-theme
   #:get-premium-emoji-statuses
   #:fetch-premium-emoji-statuses
   #:set-emoji-status
   #:clear-emoji-status
   #:get-premium-transcription-hours
   #:transcribe-voice-message-premium
   #:get-doubled-limits
   #:can-pin-more-chats-p
   #:can-join-more-channels-p
   #:render-premium-badge
   #:render-premium-features-panel
   #:show-premium-promo
   #:get-premium-stats
   #:reset-premium-cache
   #:get-premium-subscription-info
   #:cancel-premium-subscription
   #:renew-premium-subscription

   ;; Performance Optimizations v2
   #:batch-get-users-no-cons
   #:batch-insert-messages-no-cons
   #:format-chat-id-fast
   #:concat-strings-fast
   #:keyword-from-string-fast
   #:*cache-locks*
   #:*cache-lock-global*
   #:with-cache-lock
   #:safe-get-cache
   #:safe-set-cache
   #:safe-remove-cache
   #:ensure-database-connection
   #:with-database-transaction
   #:write-uint32-le
   #:write-uint64-le
   #:read-uint32-le
   #:read-uint64-le
   #:make-message-plist
   #:filter-messages-by-date
   #:sort-messages-by-date
   #:*connection-pool-stats*
   #:record-connection-stats
   #:get-connection-pool-stats
   #:reset-connection-pool-stats
   #:telegram-error
   #:telegram-auth-error
   #:telegram-network-error
   #:telegram-database-error
   #:telegram-error-code
   #:telegram-error-message
   #:handle-telegram-error
   #:safe-api-call
   #:time-operation
   #:get-memory-usage
   #:truncate-text
   #:normalize-phone-number
   #:fix-message-entities
   #:validate-chat-id
   #:validate-user-id
   #:cleanup-old-cache
   #:vacuum-all-caches

   ;; Object Pooling and Upload Management
   #:*object-pools*
   #:object-pool
   #:make-object-pool
   #:pool-acquire
   #:pool-release
   #:pool-initialize
   #:byte-buffer
   #:make-byte-buffer
   #:reset-byte-buffer
   #:ensure-buffer-capacity
   #:upload-session
   #:*active-uploads*
   #:*upload-part-size*
   #:*max-premium-file-size*
   #:*max-free-file-size*
   #:calculate-optimal-part-size
   #:start-file-upload
   #:upload-file-part
   #:get-upload-progress
   #:pause-upload
   #:resume-upload
   #:cancel-upload
   #:cleanup-completed-uploads

   ;; Stories Thumbnail Cache
   #:*stories-thumbnail-cache*
   #:*stories-thumbnail-max-size*
   #:*current-thumbnail-cache-size*
   #:story-thumbnail
   #:cache-story-thumbnail
   #:get-cached-story-thumbnail
   #:evict-oldest-thumbnails
   #:clear-story-thumbnail-cache
   #:preload-stories-thumbnails

   ;; Notifications (v0.22.0)
   #:notification-settings
   #:chat-notification-settings
   #:notification
   #:notification-center
   #:initialize-notification-settings
   #:get-notification-settings
   #:update-notification-settings
   #:set-custom-notification-sound
   #:get-chat-notification-settings
   #:set-chat-notification-settings
   #:mute-chat
   #:unmute-chat
   #:chat-muted-p
   #:initialize-notification-center
   #:add-notification
   #:get-notifications
   #:mark-notification-read
   #:mark-all-notifications-read
   #:clear-notifications
   #:show-desktop-notification
   #:register-notification-hook
   #:unregister-notification-hook
   #:get-server-notification-settings
   #:set-server-notification-settings
   #:export-notification-settings
   #:import-notification-settings

   ;; Contacts Enhanced (v0.22.0)
   #:contact-vcard
   #:contact-suggestion
   #:contact-import-result
   #:blocked-user
   #:make-vcard-from-user
   #:export-contact-vcard
   #:parse-vcard
   #:import-contact-vcard
   #:export-all-contacts
   #:import-contacts
   #:delete-contacts
   #:get-contacts-status
   #:sync-contacts
   #:get-contact-sync-status
   #:get-contact-suggestions
   #:dismiss-contact-suggestion
   #:get-blocked-users
   #:block-user
   #:unblock-user
   #:user-blocked-p
   #:share-contact
   #:request-contact
   #:get-nearby-users
   #:toggle-nearby-users

   ;; Utilities (v0.22.0)
   #:format-message-text
   #:parse-message-entities
   #:strip-markdown
   #:truncate-text
   #:escape-markdown
   #:format-relative-time
   #:format-datetime
   #:parse-datetime
   #:time-to-minutes
   #:minutes-to-time
   #:make-mention
   #:parse-mention
   #:extract-mentions
   #:make-chat-link
   #:parse-chat-link
   #:rate-limiter
   #:make-rate-limiter
   #:rate-limit-try
   #:rate-limit-wait
   #:rate-limit-status
   #:*log-level*
   #:*log-output*
   #:*log-prefix*
   #:set-log-level
   #:log-message
   #:enable-debug-logging
   #:disable-debug-logging
   #:with-logging
   #:debug-time
   #:config-manager
   #:make-config-manager
   #:get-config
   #:set-config
   #:load-config
   #:save-config
   #:delete-config
   #:with-connection
   #:with-retry
   #:define-api-function

   ;; Bot API 8.0 Features (November 2024)
   ;; Message Reactions
   #:reaction-type
   #:reaction-count
   #:message-reaction-update
   #:*available-reaction-types*
   #:*reaction-update-handlers*
   #:make-reaction-type-emoji
   #:make-reaction-type-custom-emoji
   #:make-reaction-type-star
   #:send-message-reaction
   #:get-message-reactions
   #:remove-message-reaction
   #:get-available-reactions
   #:on-message-reaction
   #:unregister-reaction-handler
   #:process-reaction-update
   #:reaction-to-tl
   #:parse-reaction-from-tl

   ;; Emoji Status
   #:emoji-status
   #:*user-emoji-status*
   #:*available-emoji-statuses*
   #:set-emoji-status
   #:clear-emoji-status
   #:get-emoji-statuses
   #:get-user-emoji-status

   ;; Advanced Media Editing
   #:media-edit-options
   #:media-edit-crop
   #:media-edit-rotation
   #:media-edit-filter
   #:media-edit-overlay-text
   #:media-edit-overlay-emoji
   #:media-edit-caption
   #:media-edit-parse-mode
   #:edit-message-media-advanced
   #:crop-media
   #:rotate-media
   #:apply-media-filter
   #:add-text-overlay
   #:add-emoji-sticker
   #:edit-message-caption
   #:filter-type
   #:get-available-filters
   #:apply-filter-by-name

   ;; Story Highlights
   #:story-highlight
   #:highlight-cover
   #:story-highlight-id
   #:story-highlight-title
   #:story-highlight-cover
   #:story-highlight-stories
   #:story-highlight-date-created
   #:story-highlight-is-hidden
   #:story-highlight-privacy
   #:highlight-cover-media-id
   #:highlight-cover-crop
   #:highlight-cover-filter
   #:create-highlight
   #:edit-highlight
   #:edit-highlight-cover
   #:reorder-highlights
   #:get-highlights
   #:delete-highlight
   #:set-highlight-privacy
   #:add-stories-to-highlight
   #:remove-highlight
   #:parse-highlight-from-tl

   ;; Message Translation
   #:translation-result
   #:translation-original-text
   #:translation-translated-text
   #:translation-source-language
   #:translation-target-language
   #:translation-auto-detected
   #:translate-message
   #:translate-text
   #:set-chat-language
   #:get-supported-languages
   #:clear-translation-cache
   #:get-translation-history
   #:enable-auto-translation
   #:disable-auto-translation
   #:auto-translation-enabled-p
   #:supported-translation-languages

   ;; Bot API 8.1-8.3 Extensions (2025)
   ;; Verification Features (8.2)
   #:verification-result
   #:verification-success
   #:verification-description
   #:verification-id
   #:verification-date
   #:verification-verified-by
   #:verify-user
   #:verify-chat
   #:remove-user-verification
   #:remove-chat-verification

   ;; Gift Features (8.3)
   #:gift
   #:gifts
   #:transaction-partner-chat
   #:gift-id
   #:gift-name
   #:gift-description
   #:gift-upgrade-star-count
   #:gift-total-count
   #:gift-owner-count
   #:gift-icon
   #:gift-is-limited
   #:gift-is-exclusive
   #:gifts-list
   #:gifts-total-count
   #:transaction-partner-chat-chat
   #:transaction-partner-chat-amount
   #:transaction-partner-chat-transaction-id
   #:transaction-partner-chat-date
   #:*available-gifts-cache*
   #:*gifts-cache-ttl*
   #:*gifts-last-fetch*
   #:get-available-gifts
   #:send-gift
   #:clear-gifts-cache

   ;; Video Enhancements (8.3)
   #:video-cover
   #:video-cover-media-id
   #:video-cover-media-type
   #:video-cover-timestamp
   #:video-cover-file-id
   #:send-video  ; Enhanced with cover and start-timestamp
   #:forward-message-with-timestamp
   #:copy-message-with-timestamp

   ;; Business Features (8.1)
   #:business-connection
   #:business-intro
   #:business-location
   #:business-opening-hours
   #:business-opening-hours-interval
   #:business-connection-id
   #:business-connection-user
   #:business-connection-user-chat-id
   #:business-connection-user-username
   #:business-connection-date
   #:business-connection-can-reply
   #:business-connection-is-enabled
   #:business-connection-has-main-username
   #:business-intro-title
   #:business-intro-message
   #:business-intro-sticker-id
   #:business-location-address
   #:business-location-latitude
   #:business-location-longitude
   #:business-location-name
   #:business-opening-hours-schedule
   #:business-opening-hours-timezone
   #:business-opening-hours-intervals
   #:business-interval-start-minute
   #:business-interval-end-minute
   #:*business-connections-cache*
   #:get-business-connection
   #:get-business-intro
   #:get-business-location
   #:get-business-opening-hours
   #:clear-business-connection-cache
   #:business-connection-cached-p

   ;; Service Message Reactions (8.3)
   #:send-service-message-reaction

   ;; Bot API 9.4-9.6 Features (2026)
   ;; Custom Emoji Messages (9.4)
   #:custom-emoji-sticker
   #:custom-emoji-pack
   #:custom-emoji-sticker-id
   #:custom-emoji-emoji
   #:custom-emoji-animation
   #:custom-emoji-thumbnail
   #:custom-emoji-width
   #:custom-emoji-height
   #:custom-emoji-file-size
   #:emoji-pack-id
   #:emoji-pack-title
   #:emoji-pack-emojis
   #:emoji-pack-is-official
   #:emoji-pack-owner-id
   #:emoji-pack-sticker-count
   #:*custom-emoji-cache*
   #:*emoji-pack-cache*
   #:get-custom-emoji-sticker
   #:send-custom-emoji-message
   #:get-custom-emoji-pack
   #:list-custom-emoji-packs
   #:add-custom-emoji-to-pack
   #:delete-custom-emoji
   #:create-custom-emoji-pack
   #:clear-custom-emoji-cache
   #:get-custom-emoji-cache-stats

   ;; Enhanced Message Content (9.4)
   #:interactive-content
   #:interactive-poll
   #:quiz-poll
   #:interactive-content-type
   #:interactive-message-id
   #:interactive-chat-id
   #:interactive-data
   #:poll-question
   #:poll-options
   #:poll-total-voters
   #:poll-is-anonymous
   #:poll-allows-multiple
   #:quiz-correct-option
   #:quiz-explanation
   #:get-enhanced-message-content
   #:parse-interactive-content
   #:create-interactive-poll
   #:create-quiz-mode
   #:get-poll-results

   ;; Animated Emoji (9.4)
   #:send-animated-emoji
   #:get-available-emoji
   #:get-emoji-status
   #:set-emoji-status

   ;; Bot API 9.5 - DateTime Entity
   #:datetime-entity
   #:datetime-value
   #:datetime-timezone
   #:datetime-format
   #:datetime-display-text
   #:make-datetime-entity
   #:parse-datetime-entity
   #:format-datetime-display
   #:get-timezone-aware-datetime
   #:convert-datetime-timezone

   ;; Bot API 9.5 - Managed Bots
   #:managed-bot-info
   #:token-change-notification
   #:managed-bot-id
   #:managed-org-id
   #:managed-bot-status
   #:managed-token-date
   #:token-change-bot-id
   #:token-change-type
   #:token-change-date
   #:token-change-by
   #:register-managed-bot
   #:get-bot-management-status
   #:update-bot-credentials
   #:handle-token-change-notification
   #:get-token-change-history
   #:get-managed-bot-info
   #:unregister-managed-bot

   ;; Bot API 9.6 - Mini App Device Access
   #:request-camera-access
   #:request-microphone-access
   #:capture-photo
   #:capture-video
   #:get-media-stream
   #:release-media-stream
   #:get-device-permissions
   #:check-device-support
   #:initialize-mini-app
   #:shutdown-mini-app
   #:get-mini-app-stats
   #:clear-mini-app-cache
   #:create-mini-app-button
   #:show-mini-app-alert

   ;; Bot API 9.6 - Mini App Theme
   #:mini-app-theme
   #:mini-app-bg-color
   #:mini-app-text-color
   #:mini-app-hint-color
   #:mini-app-link-color
   #:mini-app-button-color
   #:mini-app-secondary-bg
   #:mini-app-header-bg
   #:mini-app-is-dark
   #:get-mini-app-theme
   #:sync-with-client-theme
   #:apply-theme-to-clog
   #:apply-theme-parameters
   #:on-theme-change
   #:get-theme-parameters
   #:set-theme-override

   ;; Bot API 9.7 - Location API
   #:request-location-access
   #:get-current-location
   #:watch-position
   #:clear-position-watch

   ;; Bot API 9.7 - File Picker
   #:select-files
   #:select-directory
   #:read-file-content

   ;; Bot API 9.7 - Notification API
   #:request-notification-permission
   #:get-notification-permission
   #:send-notification
   #:on-notification-click
   #:close-notification

   ;; Bot API 9.7 - Stats and Cleanup
   #:get-bot-api-9-7-stats
   #:clear-location-cache
   #:clear-notification-cache
   #:initialize-bot-api-9-7

   ;; Bot API 9.7+ - Mini App Enhanced (Haptic, Clipboard, Share)
   #:haptic-feedback-impact
   #:haptic-feedback-notification
   #:haptic-feedback-selection-change
   #:read-clipboard-text
   #:write-clipboard-text
   #:read-clipboard-files
   #:on-share-target-received
   #:get-shared-data
   #:share-text
   #:share-file
   #:can-share-p
   #:clear-mini-app-enhanced-cache
   #:get-mini-app-enhanced-stats
   #:initialize-mini-app-enhanced

   ;; Bot API 9.7+ - Advanced Features (Biometric, Contacts)
   #:is-biometric-available
   #:request-biometric-auth
   #:enroll-biometric
   #:is-biometric-enrolled-p
   #:is-contacts-api-supported
   #:select-contacts
   #:get-contact-details
   #:clear-contacts-cache
   #:expand-web-app
   #:close-web-app
   #:toggle-web-app-confirmation
   #:setup-main-button
   #:on-main-button-click
   #:clear-biometric-cache
   #:clear-advanced-cache
   #:get-advanced-stats
   #:initialize-bot-api-9-advanced

   ;; Performance Optimizations v4
   #:make-connection-pool
   #:initialize-connection-pool
   #:get-pool
   #:acquire-connection
   #:release-connection
   #:close-pool
   #:get-pool-stats
   #:batch-rpc-call
   #:enqueue-batch-request
   #:flush-batch-queue
   #:start-batch-processor
   #:stop-batch-processor
   #:defer-execution
   #:cancel-deferred-execution
   #:get-incremental-updates
   #:apply-incremental-update
   #:sync-incremental
   #:get-performance-stats
   #:clear-performance-cache
   #:initialize-performance-optimizations-v4
   #:shutdown-performance-optimizations-v4

   ;; File Management Enhanced (v0.31.0)
   #:make-upload-session
   #:upload-file-chunk
   #:get-upload-status
   #:cancel-upload-session
   #:complete-upload-session
   #:make-download-session
   #:download-file-chunk
   #:resume-download
   #:pause-download
   #:get-media-metadata
   #:extract-video-thumbnail
   #:get-file-info
   #:initialize-file-cache
   #:get-cache-entry
   #:cache-file
   #:get-cached-file
   #:clear-file-cache
   #:get-file-cache-stats
   #:get-active-uploads-stats
   #:get-active-downloads-stats
   #:get-performance-file-stats
   #:cleanup-stale-sessions
   #:initialize-file-management-enhanced
   #:shutdown-file-management-enhanced
   #:*max-concurrent-uploads*
   #:*max-concurrent-downloads*
   #:*default-chunk-size*

   ;; Payment and Stars Enhanced (v0.31.0)
   #:create-star-invoice
   #:send-star-invoice
   #:get-invoice-status
   #:process-star-payment
   #:get-star-balance
   #:send-star-payment
   #:get-star-transactions
   #:refund-star-payment
   #:make-paid-media-info
   #:send-paid-media
   #:get-paid-media-post
   #:create-star-giveaway
   #:join-giveaway
   #:select-giveaway-winners
   #:get-giveaway-status
   #:convert-star-gift
   #:get-payment-stats
   #:get-giveaway-stats
   #:initialize-payment-stars
   #:shutdown-payment-stars
   #:*star-invoices*
   #:*star-payments*
   #:*star-giveaways*

   ;; Account Security Enhanced (v0.31.0)
   #:generate-qr-login-token
   #:get-qr-code-image
   #:check-qr-login-status
   #:import-qr-login-token
   #:accept-qr-login-token
   #:get-2fa-status
   #:enable-two-factor-auth
   #:disable-two-factor-auth
   #:change-two-factor-password
   #:verify-two-factor-auth
   #:get-active-sessions
   #:terminate-session
   #:terminate-all-sessions
   #:get-privacy-settings
   #:set-privacy-setting
   #:get-privacy-visibility
   #:get-current-phone-number
   #:change-phone-number
   #:confirm-phone-number
   #:get-security-stats
   #:initialize-account-security-enhanced
   #:shutdown-account-security-enhanced
   #:*qr-login-tokens*
   #:*2fa-info*))
